import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import DatePickerContext from '../components/date-picker-context'
import Nav from './nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Temperature Blanket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DatePickerContext>
          <main className="flex flex-col min-h-screen h-screen bg-slate-50 dark:bg-slate-900">
            <Nav />
            {children}
          </main>
        </DatePickerContext>
      </body>
    </html>
  )
}
